// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNote'](arg1, arg2, arg3);
}

export function AddSubtitle(arg1) {
  return window['go']['main']['App']['AddSubtitle'](arg1);
}

export function AddToPlaylist(arg1) {
  return window['go']['main']['App']['AddToPlaylist'](arg1);
}

export function Chapters() {
  return window['go']['main']['App']['Chapters']();
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function ChooseFile() {
  return window['go']['main']['App']['ChooseFile']();
}

export function ChooseFiles() {
  return window['go']['main']['App']['ChooseFiles']();
}

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function ChooseSubtitle() {
  return window['go']['main']['App']['ChooseSubtitle']();
}

export function ClearPlaylist() {
  return window['go']['main']['App']['ClearPlaylist']();
}

export function ClearRecent() {
  return window['go']['main']['App']['ClearRecent']();
}

export function CurrentPath() {
  return window['go']['main']['App']['CurrentPath']();
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function Diagnostics() {
  return window['go']['main']['App']['Diagnostics']();
}

export function DisableSubtitles() {
  return window['go']['main']['App']['DisableSubtitles']();
}

export function ExportPlaylist() {
  return window['go']['main']['App']['ExportPlaylist']();
}

export function ForgetRecent(arg1) {
  return window['go']['main']['App']['ForgetRecent'](arg1);
}

export function HandleDrop(arg1) {
  return window['go']['main']['App']['HandleDrop'](arg1);
}

export function ImportPlaylist() {
  return window['go']['main']['App']['ImportPlaylist']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsFullscreen() {
  return window['go']['main']['App']['IsFullscreen']();
}

export function LoadNotesFrom() {
  return window['go']['main']['App']['LoadNotesFrom']();
}

export function LogClientError(arg1) {
  return window['go']['main']['App']['LogClientError'](arg1);
}

export function LogClientInfo(arg1) {
  return window['go']['main']['App']['LogClientInfo'](arg1);
}

export function MediaInfo() {
  return window['go']['main']['App']['MediaInfo']();
}

export function NextTrack() {
  return window['go']['main']['App']['NextTrack']();
}

export function NoteAt(arg1) {
  return window['go']['main']['App']['NoteAt'](arg1);
}

export function Notes() {
  return window['go']['main']['App']['Notes']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function PlayPause() {
  return window['go']['main']['App']['PlayPause']();
}

export function PlayPlaylistItem(arg1) {
  return window['go']['main']['App']['PlayPlaylistItem'](arg1);
}

export function Playlist() {
  return window['go']['main']['App']['Playlist']();
}

export function PreviousTrack() {
  return window['go']['main']['App']['PreviousTrack']();
}

export function RecentFiles() {
  return window['go']['main']['App']['RecentFiles']();
}

export function RemoveFromPlaylist(arg1) {
  return window['go']['main']['App']['RemoveFromPlaylist'](arg1);
}

export function ReplacePlaylist(arg1) {
  return window['go']['main']['App']['ReplacePlaylist'](arg1);
}

export function SaveNotesAs() {
  return window['go']['main']['App']['SaveNotesAs']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWindowState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2, arg3, arg4, arg5);
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}

export function SeekChapter(arg1) {
  return window['go']['main']['App']['SeekChapter'](arg1);
}

export function SeekRelative(arg1) {
  return window['go']['main']['App']['SeekRelative'](arg1);
}

export function SetAudioDelay(arg1) {
  return window['go']['main']['App']['SetAudioDelay'](arg1);
}

export function SetAudioTrack(arg1) {
  return window['go']['main']['App']['SetAudioTrack'](arg1);
}

export function SetAutoResume(arg1) {
  return window['go']['main']['App']['SetAutoResume'](arg1);
}

export function SetCheckForUpdates(arg1) {
  return window['go']['main']['App']['SetCheckForUpdates'](arg1);
}

export function SetFollowTranscript(arg1) {
  return window['go']['main']['App']['SetFollowTranscript'](arg1);
}

export function SetFullscreen(arg1) {
  return window['go']['main']['App']['SetFullscreen'](arg1);
}

export function SetMute(arg1) {
  return window['go']['main']['App']['SetMute'](arg1);
}

export function SetRepeat(arg1) {
  return window['go']['main']['App']['SetRepeat'](arg1);
}

export function SetReverse(arg1) {
  return window['go']['main']['App']['SetReverse'](arg1);
}

export function SetShuffle(arg1) {
  return window['go']['main']['App']['SetShuffle'](arg1);
}

export function SetSidePanel(arg1, arg2) {
  return window['go']['main']['App']['SetSidePanel'](arg1, arg2);
}

export function SetSpeed(arg1) {
  return window['go']['main']['App']['SetSpeed'](arg1);
}

export function SetSubtitleDelay(arg1) {
  return window['go']['main']['App']['SetSubtitleDelay'](arg1);
}

export function SetSubtitleScale(arg1) {
  return window['go']['main']['App']['SetSubtitleScale'](arg1);
}

export function SetSubtitleTrack(arg1) {
  return window['go']['main']['App']['SetSubtitleTrack'](arg1);
}

export function SetVideoBounds(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetVideoBounds'](arg1, arg2, arg3, arg4, arg5);
}

export function SetVideoVisible(arg1) {
  return window['go']['main']['App']['SetVideoVisible'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function SkipUpdate(arg1) {
  return window['go']['main']['App']['SkipUpdate'](arg1);
}

export function SpeedPresets() {
  return window['go']['main']['App']['SpeedPresets']();
}

export function State() {
  return window['go']['main']['App']['State']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleMute() {
  return window['go']['main']['App']['ToggleMute']();
}

export function ToggleNoteStar(arg1) {
  return window['go']['main']['App']['ToggleNoteStar'](arg1);
}

export function ToggleReverse() {
  return window['go']['main']['App']['ToggleReverse']();
}

export function ToolStatus() {
  return window['go']['main']['App']['ToolStatus']();
}

export function Tracks() {
  return window['go']['main']['App']['Tracks']();
}

export function Transcript() {
  return window['go']['main']['App']['Transcript']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
