// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {playlist} from '../models';
import {player} from '../models';
import {notes} from '../models';
import {history} from '../models';
import {settings} from '../models';

export function AddNote(arg1:number,arg2:string,arg3:boolean):Promise<main.NotesResult>;

export function AddSubtitle(arg1:string):Promise<void>;

export function AddToPlaylist(arg1:Array<string>):Promise<playlist.State>;

export function Chapters():Promise<Array<player.Chapter>>;

export function CheckForUpdates(arg1:boolean):Promise<main.UpdateInfo>;

export function ChooseFile():Promise<string>;

export function ChooseFiles():Promise<Array<string>>;

export function ChooseFolder():Promise<string>;

export function ChooseSubtitle():Promise<string>;

export function ClearPlaylist():Promise<playlist.State>;

export function ClearRecent():Promise<void>;

export function CurrentPath():Promise<string>;

export function DeleteNote(arg1:number):Promise<main.NotesResult>;

export function Diagnostics():Promise<main.Diagnostics>;

export function DisableSubtitles():Promise<void>;

export function ExportPlaylist():Promise<string>;

export function ForgetRecent(arg1:string):Promise<void>;

export function HandleDrop(arg1:Array<string>):Promise<void>;

export function ImportPlaylist():Promise<playlist.State>;

export function InstallUpdate():Promise<void>;

export function IsFullscreen():Promise<boolean>;

export function LoadNotesFrom():Promise<main.NotesResult>;

export function LogClientError(arg1:string):Promise<void>;

export function LogClientInfo(arg1:string):Promise<void>;

export function MediaInfo():Promise<player.MediaInfo>;

export function NextTrack():Promise<void>;

export function NoteAt(arg1:number):Promise<notes.Note>;

export function Notes():Promise<main.NotesResult>;

export function Open(arg1:string):Promise<main.OpenResult>;

export function OpenReleasePage():Promise<void>;

export function Pause():Promise<void>;

export function Play():Promise<void>;

export function PlayPause():Promise<void>;

export function PlayPlaylistItem(arg1:number):Promise<playlist.State>;

export function Playlist():Promise<playlist.State>;

export function PreviousTrack():Promise<void>;

export function RecentFiles():Promise<Array<history.Entry>>;

export function RemoveFromPlaylist(arg1:number):Promise<playlist.State>;

export function ReplacePlaylist(arg1:Array<string>):Promise<playlist.State>;

export function SaveNotesAs():Promise<main.NotesResult>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function SaveWindowState(arg1:number,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SeekChapter(arg1:number):Promise<void>;

export function SeekRelative(arg1:number):Promise<void>;

export function SetAudioDelay(arg1:number):Promise<void>;

export function SetAudioTrack(arg1:number):Promise<void>;

export function SetAutoResume(arg1:boolean):Promise<void>;

export function SetCheckForUpdates(arg1:boolean):Promise<void>;

export function SetFollowTranscript(arg1:boolean):Promise<void>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function SetMute(arg1:boolean):Promise<void>;

export function SetRepeat(arg1:string):Promise<playlist.State>;

export function SetReverse(arg1:boolean):Promise<void>;

export function SetShuffle(arg1:boolean):Promise<playlist.State>;

export function SetSidePanel(arg1:boolean,arg2:number):Promise<void>;

export function SetSpeed(arg1:number):Promise<void>;

export function SetSubtitleDelay(arg1:number):Promise<void>;

export function SetSubtitleScale(arg1:number):Promise<void>;

export function SetSubtitleTrack(arg1:number):Promise<void>;

export function SetVideoBounds(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function SetVideoVisible(arg1:boolean):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function Settings():Promise<settings.Settings>;

export function SkipUpdate(arg1:string):Promise<void>;

export function SpeedPresets():Promise<Array<number>>;

export function State():Promise<player.PlaybackState>;

export function Stop():Promise<void>;

export function ToggleMute():Promise<void>;

export function ToggleNoteStar(arg1:number):Promise<main.NotesResult>;

export function ToggleReverse():Promise<void>;

export function ToolStatus():Promise<Array<string>>;

export function Tracks():Promise<Array<player.Track>>;

export function Transcript():Promise<main.TranscriptResult>;

export function Version():Promise<main.UpdateInfo>;
